// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/complete-profile" | "/dashboard/compliance" | "/dashboard/data-eksport" | "/dashboard/fremtiden" | "/dashboard/indstillinger" | "/dashboard/join-requests" | "/dashboard/notifikationer" | "/dashboard/regler" | "/landing" | "/login" | "/pending-approval" | "/select-role" | "/select-workplace" | "/super-admin" | "/super-admin/helligdage" | "/super-admin/notifications-broadcast" | "/super-admin/support" | "/super-admin/translations" | "/super-admin/users" | "/super-admin/workplace-templates" | "/super-admin/workplaces/[id]" | "/super-admin/workplaces/new" | "/test-ai"
type AppRouteHandlerRoutes = "/api/ai/explain" | "/api/solver" | "/auth/callback" | "/landing-employee-photo" | "/landing-eu-compliance" | "/landing-hero" | "/landing-logo"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/select-role" | "/select-workplace" | "/super-admin"
type RedirectRoutes = never
type RewriteRoutes = "/favicon.ico"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/explain": {}
  "/api/solver": {}
  "/auth/callback": {}
  "/dashboard": {}
  "/dashboard/complete-profile": {}
  "/dashboard/compliance": {}
  "/dashboard/data-eksport": {}
  "/dashboard/fremtiden": {}
  "/dashboard/indstillinger": {}
  "/dashboard/join-requests": {}
  "/dashboard/notifikationer": {}
  "/dashboard/regler": {}
  "/favicon.ico": {}
  "/landing": {}
  "/landing-employee-photo": {}
  "/landing-eu-compliance": {}
  "/landing-hero": {}
  "/landing-logo": {}
  "/login": {}
  "/pending-approval": {}
  "/select-role": {}
  "/select-workplace": {}
  "/super-admin": {}
  "/super-admin/helligdage": {}
  "/super-admin/notifications-broadcast": {}
  "/super-admin/support": {}
  "/super-admin/translations": {}
  "/super-admin/users": {}
  "/super-admin/workplace-templates": {}
  "/super-admin/workplaces/[id]": { "id": string; }
  "/super-admin/workplaces/new": {}
  "/test-ai": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/select-role": never
  "/select-workplace": never
  "/super-admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
