-- Delmængde af supabase_seed_ui_translations_app.sql: admin-menu + Compliance-siden.
-- Kør i Supabase SQL Editor når en-US rækker mangler i /super-admin/translations (idempotent).
-- Fuld app-seed: supabase_seed_ui_translations_app.sql

insert into public.ui_translations (translation_key, language_code, text_value, context_description) values

('admin.nav.compliance', 'en-US', 'Compliance', 'Admin sidebar navigation label (AdminWorkspaceShell → /dashboard/compliance). Short noun; legal/regulatory documentation area (GDPR, EU AI Act, tenant-specific notes). Not a certification or guarantee of compliance.'),
('admin.nav.compliance', 'da', 'Compliance', 'Admin-menu: link til /dashboard/compliance. Kort navn; lov-/GDPR-/AI-orienteret dokumentation — ikke en erklæring om at krav er opfyldt.'),

-- Compliance (lovpligtig / rullende dokumentation). Kildesprog i /super-admin/translations er en-US — kør seed hvis nøgler mangler.
('compliance.page.title', 'en-US', 'Compliance', 'Page title (h1) on /dashboard/compliance (admin area). Should align with sidebar label admin.nav.compliance.'),
('compliance.page.title', 'da', 'Compliance', 'Overskrift på compliance-siden; samme begreb som admin-menuen.'),
('compliance.page.intro', 'en-US', 'This area provides rolling, legally oriented documentation for ShiftBob: transparency about how the system works, references to AI and data-protection requirements, and a section for your organisation’s use of the product. Content will be updated as legislation and product features evolve.', 'Lead paragraph under h1 on /dashboard/compliance. Neutral, informational tone (not legal advice). Mentions ShiftBob as product name; describes rolling updates and tenant-specific section.'),
('compliance.page.intro', 'da', 'Her finder du løbende, lovmæssigt orienteret dokumentation for ShiftBob: transparens om systemets virkemåde, henvisning til krav om kunstig intelligens og databeskyttelse samt et afsnit om jeres konkrete brug. Indholdet opdateres, efterhånden som lovgivning og produktet udvikler sig.', 'Indledning; produktnavn ShiftBob bevares.'),
('compliance.section.system_title', 'en-US', 'System overview & transparency', 'First main section heading (h2) on /dashboard/compliance: high-level description of the system and transparency.'),
('compliance.section.system_title', 'da', 'Overordnet system og transparens', 'Sektionsoverskrift (h2).'),
('compliance.section.system_body', 'en-US', 'ShiftBob is a workplace scheduling application. Data is processed to provide calendars, roles, notifications and (where enabled) AI-assisted features such as plan suggestions or text generation. Processing is limited to what is needed for these purposes. Technical and organisational measures follow the design of the underlying platform (e.g. Supabase: authentication, row-level security, encryption in transit). This description is high-level; detailed data-flow diagrams and subprocessors can be listed here as the documentation matures.', 'Body under system section. Keep ShiftBob and Supabase as proper nouns. RLS = row-level security; explain or expand in target language if needed. Not legal advice.'),
('compliance.section.system_body', 'da', 'ShiftBob er en arbejdsplads-app til vagtplanlægning. Data behandles for at levere kalendere, roller, notifikationer og (hvor det er slået til) AI-understøttede funktioner såsom planforslag eller tekstgenerering. Behandlingen er begrænset til det, der er nødvendigt for disse formål. Tekniske og organisatoriske foranstaltninger følger den underliggende platforms udformning (fx Supabase: login, række-sikkerhed, kryptering under transport). Beskrivelsen er overordnet; detaljerede dataflows og underdatabehandlere kan uddybes her, efterhånden som dokumentationen modnes.', 'Brødtekst; produkt- og platformnavne bevares.'),
('compliance.section.ai_title', 'en-US', 'Artificial intelligence (EU AI Act)', 'Section heading (h2): AI use and EU Artificial Intelligence Act framing.'),
('compliance.section.ai_title', 'da', 'Kunstig intelligens (EU’s AI-forordning)', 'Sektionsoverskrift (h2).'),
('compliance.section.ai_body', 'en-US', 'Where ShiftBob uses AI (e.g. schedule explanations, import helpers, or future planning tools), outputs support human decisions and should be verified by responsible staff. High-risk automated decisions without human oversight are not the intended use. As EU AI Act obligations are clarified for your sector and deployment, this section will summarise the role of AI in the product, logging where applicable, and how to exercise rights or contest outcomes. Update this page after legal review.', 'Body: human oversight, not standalone high-risk automation; obligations may evolve; recommend legal review. Formal compliance-oriented tone.'),
('compliance.section.ai_body', 'da', 'Når ShiftBob anvender AI (fx forklaringer af planer, import-hjælp eller fremtidige planlægningsværktøjer), er resultaterne et beslutningsgrundlag for mennesker og bør kontrolleres af ansvarlige medarbejdere. Fuldt automatiserede afgørelser uden menneskelig inddragelse er ikke den tilsigtede anvendelse. Efterhånden som forpligtelser under EU’s AI-forordning afklares for jeres sektor og drift, vil dette afsnit blive opdateret med produktets rolle, relevant logning og hvordan brugerne kan gøre indsigelse. Indhold bør juridisk kvalificeres.', 'Brødtekst; formel tone.'),
('compliance.section.gdpr_title', 'en-US', 'Personal data & GDPR', 'Section heading (h2): GDPR and personal data processing.'),
('compliance.section.gdpr_title', 'da', 'Persondata og GDPR', 'Sektionsoverskrift (h2).'),
('compliance.section.gdpr_body', 'en-US', 'ShiftBob processes personal data such as identity, contact, work role, schedule and preferences to deliver the service. The data controller for your organisation’s use is typically your employer or the entity named in the agreement; ShiftBob acts according to the agreed setup (often as processor when we provide the software). Lawful bases, retention, transfers, DPIA and records of processing should be documented in your organisation’s privacy materials and cross-referenced here. Data subjects’ rights (access, rectification, erasure, restriction, portability, objection) are supported through account and admin flows where technically possible.', 'Body: controller vs processor (typical pattern), DPIA, RoPA, data subject rights. EU GDPR framing; not legal advice; customer must document their own legal basis.'),
('compliance.section.gdpr_body', 'da', 'ShiftBob behandler personoplysninger såsom identitet, kontakt, arbejdsrolle, vagtplan og præferencer for at levere tjenesten. Dataansvarlig for jeres brug er typisk arbejdsgiveren eller den enhed, der fremgår af aftalen; ShiftBob agerer efter den aftalte rolle (ofte som databehandler). Lovlige grunde, opbevaring, overførsler, DPIA og behandlingsaktiviteter bør dokumenteres i jeres egen privatlivs-/compliance-materiale og kan refereres her. Registreredes rettigheder (indsigt, berigtigelse, sletning, begrænsning, dataportabilitet, indsigelse) understøttes gennem konto- og admin-flows, hvor det er teknisk muligt.', 'Brødtekst.'),
('compliance.section.tenant_title', 'en-US', 'Your organisation’s use', 'Section heading (h2): customer/tenant-specific compliance and usage.'),
('compliance.section.tenant_title', 'da', 'Jeres brug af systemet', 'Sektionsoverskrift (h2).'),
('compliance.section.tenant_body', 'en-US', 'Active workplace: {workplace}. This section will hold customer-specific compliance artefacts: configuration of AI features, data categories in use, retention choices, DPIA excerpts, and audit trails as they become available in the product. Until automated exports are linked here, document decisions internally and keep this page as the single entry point for regulators and DPO reviews.', 'Body; placeholder {workplace} is replaced in code with the active workplace display name — preserve {workplace} exactly in all translations.'),
('compliance.section.tenant_body', 'da', 'Aktiv arbejdsplads: {workplace}. Dette afsnit skal indeholde kundespecifik compliance: aktivering af AI-funktioner, hvilke datakategorier I bruger, opbevaringsvalg, uddrag af DPIA og revisionspor, efterhånden som det bliver tilgængeligt i produktet. Indtil automatiske udtræk kobles på, bør I dokumentere beslutninger internt og bruge denne side som fælles indgang for tilsyn og DPO-gennemgang.', 'Bevar pladsholderen {workplace} uændret.'),
('compliance.footer.rolling', 'en-US', 'Rolling compliance: this page is a living document. Last content review: not yet recorded — assign ownership in your organisation.', 'Footer on /dashboard/compliance: reminds that content is a living document; internal process note.'),
('compliance.footer.rolling', 'da', 'Rullende compliance: denne side er et levende dokument. Seneste indholdsgennemgang: ikke registreret — udpeg ansvarlig i organisationen.', 'Bundnote; meta om vedligeholdelse.')

on conflict (translation_key, language_code) do update set
  text_value = excluded.text_value,
  context_description = excluded.context_description;
