// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/dashboard/complete-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/complete-profile">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/complete-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/compliance">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/data-eksport/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/data-eksport">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/data-eksport/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/fremtiden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fremtiden">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/fremtiden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/import-regneark/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/import-regneark">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/import-regneark/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/indstillinger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/indstillinger">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/indstillinger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/join-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/join-requests">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/join-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/notifikationer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifikationer">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/notifikationer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/regler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/regler">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/regler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employer-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer-login">> = Specific
  const handler = {} as typeof import("../../../app/employer-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employer-signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employer-signup">> = Specific
  const handler = {} as typeof import("../../../app/employer-signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../../app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pending-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pending-approval">> = Specific
  const handler = {} as typeof import("../../../app/pending-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/select-role/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-role">> = Specific
  const handler = {} as typeof import("../../../app/select-role/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/select-workplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/select-workplace">> = Specific
  const handler = {} as typeof import("../../../app/select-workplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/helligdage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/helligdage">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/helligdage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/notifications-broadcast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/notifications-broadcast">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/notifications-broadcast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/salesbot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/salesbot">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/salesbot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/support">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/translations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/translations">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/translations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/users">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/workplace-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/workplace-templates">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/workplace-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/workplaces/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/workplaces/[id]">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/workplaces/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/workplaces/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/workplaces/new">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/workplaces/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-ai">> = Specific
  const handler = {} as typeof import("../../../app/test-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/explain/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/explain">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/explain/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/salesbot/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/salesbot/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/salesbot/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/salesbot/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/salesbot/session">> = Specific
  const handler = {} as typeof import("../../../app/api/salesbot/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/salesbot/support-ticket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/salesbot/support-ticket">> = Specific
  const handler = {} as typeof import("../../../app/api/salesbot/support-ticket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/solver/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solver">> = Specific
  const handler = {} as typeof import("../../../app/api/solver/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing-employee-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/landing-employee-photo">> = Specific
  const handler = {} as typeof import("../../../app/landing-employee-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing-eu-compliance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/landing-eu-compliance">> = Specific
  const handler = {} as typeof import("../../../app/landing-eu-compliance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing-hero/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/landing-hero">> = Specific
  const handler = {} as typeof import("../../../app/landing-hero/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/landing-logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/landing-logo">> = Specific
  const handler = {} as typeof import("../../../app/landing-logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/select-role/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/select-role">> = Specific
  const handler = {} as typeof import("../../../app/select-role/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/select-workplace/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/select-workplace">> = Specific
  const handler = {} as typeof import("../../../app/select-workplace/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
