module.exports = [
"[project]/src/components/admin-workspace-shell.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "AdminWorkspaceShell",
    ()=>AdminWorkspaceShell
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const AdminWorkspaceShell = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call AdminWorkspaceShell() from the server but AdminWorkspaceShell is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/admin-workspace-shell.tsx <module evaluation>", "AdminWorkspaceShell");
}),
"[project]/src/components/admin-workspace-shell.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "AdminWorkspaceShell",
    ()=>AdminWorkspaceShell
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const AdminWorkspaceShell = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call AdminWorkspaceShell() from the server but AdminWorkspaceShell is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/admin-workspace-shell.tsx", "AdminWorkspaceShell");
}),
"[project]/src/components/admin-workspace-shell.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$admin$2d$workspace$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/admin-workspace-shell.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$admin$2d$workspace$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/admin-workspace-shell.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$admin$2d$workspace$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/components/dashboard-onboarding-guard.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "DashboardOnboardingGuard",
    ()=>DashboardOnboardingGuard
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const DashboardOnboardingGuard = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call DashboardOnboardingGuard() from the server but DashboardOnboardingGuard is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard-onboarding-guard.tsx <module evaluation>", "DashboardOnboardingGuard");
}),
"[project]/src/components/dashboard-onboarding-guard.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "DashboardOnboardingGuard",
    ()=>DashboardOnboardingGuard
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const DashboardOnboardingGuard = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call DashboardOnboardingGuard() from the server but DashboardOnboardingGuard is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard-onboarding-guard.tsx", "DashboardOnboardingGuard");
}),
"[project]/src/components/dashboard-onboarding-guard.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2d$onboarding$2d$guard$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/dashboard-onboarding-guard.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2d$onboarding$2d$guard$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/dashboard-onboarding-guard.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2d$onboarding$2d$guard$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/types/roles.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ROLES",
    ()=>ROLES,
    "isRole",
    ()=>isRole
]);
const ROLES = [
    "SUPER_ADMIN",
    "ADMIN",
    "MANAGER",
    "EMPLOYEE"
];
function isRole(value) {
    return ROLES.includes(value);
}
}),
"[project]/src/lib/roles.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ACTIVE_ROLE_COOKIE",
    ()=>ACTIVE_ROLE_COOKIE,
    "ROLE_LABELS",
    ()=>ROLE_LABELS,
    "setActiveRoleCookie",
    ()=>setActiveRoleCookie
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$js$2d$cookie$2f$dist$2f$js$2e$cookie$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/js-cookie/dist/js.cookie.mjs [app-rsc] (ecmascript)");
;
const ACTIVE_ROLE_COOKIE = "active_role";
const ROLE_LABELS = {
    SUPER_ADMIN: {
        title: "Superadmin",
        description: "Fuld adgang til system og konfiguration."
    },
    ADMIN: {
        title: "Administrator",
        description: "Administrer brugere og overordnede indstillinger."
    },
    MANAGER: {
        title: "Manager",
        description: "Led vagtplaner og team."
    },
    EMPLOYEE: {
        title: "Medarbejder",
        description: "Standard adgang til egne vagter og opgaver."
    }
};
function setActiveRoleCookie(role) {
    __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$js$2d$cookie$2f$dist$2f$js$2e$cookie$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].set(ACTIVE_ROLE_COOKIE, role, {
        path: "/",
        sameSite: "lax",
        expires: 30
    });
}
}),
"[project]/src/lib/super-admin.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "assertSuperAdminAccess",
    ()=>assertSuperAdminAccess,
    "hasSuperAdminAccess",
    ()=>hasSuperAdminAccess
]);
async function hasSuperAdminAccess(supabase) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return false;
    const { data: siteSa, error: rpcErr } = await supabase.rpc("has_super_admin_membership");
    if (!rpcErr && siteSa === true) return true;
    const { data: wm } = await supabase.from("workplace_members").select("user_id").eq("user_id", user.id).eq("role", "SUPER_ADMIN").limit(1).maybeSingle();
    if (wm) return true;
    const { data: ur, error: urErr } = await supabase.from("user_roles").select("id").eq("user_id", user.id).eq("role", "SUPER_ADMIN").limit(1).maybeSingle();
    return !urErr && !!ur;
}
async function assertSuperAdminAccess(supabase) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
        throw new Error("Ikke logget ind.");
    }
    if (!await hasSuperAdminAccess(supabase)) {
        throw new Error("Ingen adgang til Super Admin.");
    }
}
}),
"[project]/src/lib/workplaces.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ACTIVE_WORKPLACE_COOKIE",
    ()=>ACTIVE_WORKPLACE_COOKIE,
    "fetchUserRolesForWorkplace",
    ()=>fetchUserRolesForWorkplace,
    "fetchUserWorkplaces",
    ()=>fetchUserWorkplaces,
    "getActiveWorkplaceIdFromCookie",
    ()=>getActiveWorkplaceIdFromCookie,
    "routeAfterLogin",
    ()=>routeAfterLogin,
    "routeRolesForActiveWorkplace",
    ()=>routeRolesForActiveWorkplace,
    "setActiveWorkplaceCookie",
    ()=>setActiveWorkplaceCookie
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$js$2d$cookie$2f$dist$2f$js$2e$cookie$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/js-cookie/dist/js.cookie.mjs [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/types/roles.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/roles.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$super$2d$admin$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/super-admin.ts [app-rsc] (ecmascript)");
;
;
;
;
const ACTIVE_WORKPLACE_COOKIE = "active_workplace";
function setActiveWorkplaceCookie(workplaceId) {
    __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$js$2d$cookie$2f$dist$2f$js$2e$cookie$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].set(ACTIVE_WORKPLACE_COOKIE, workplaceId, {
        path: "/",
        sameSite: "lax",
        expires: 30
    });
}
function getActiveWorkplaceIdFromCookie() {
    if (typeof document === "undefined") return null;
    return __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$js$2d$cookie$2f$dist$2f$js$2e$cookie$2e$mjs__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].get(ACTIVE_WORKPLACE_COOKIE) ?? null;
}
async function fetchUserWorkplaces(supabase) {
    const { data: rpcRows, error: rpcErr } = await supabase.rpc("get_my_workplaces");
    if (!rpcErr && rpcRows != null && Array.isArray(rpcRows)) {
        return rpcRows.sort((a, b)=>a.name.localeCompare(b.name, "da"));
    }
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return [];
    const { data: mids, error: e1 } = await supabase.from("workplace_members").select("workplace_id").eq("user_id", user.id);
    if (e1) throw e1;
    const ids = [
        ...new Set((mids ?? []).map((m)=>m.workplace_id))
    ];
    if (ids.length === 0) return [];
    const { data: places, error: e2 } = await supabase.from("workplaces").select("id, name, created_at").in("id", ids);
    if (e2) throw e2;
    return (places ?? []).sort((a, b)=>a.name.localeCompare(b.name, "da"));
}
async function fetchUserRolesForWorkplace(supabase, workplaceId) {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return [];
    const { data: rpcRoles, error: rpcErr } = await supabase.rpc("get_my_roles_for_workplace", {
        p_workplace_id: workplaceId
    });
    if (!rpcErr && rpcRoles != null) {
        const raw = Array.isArray(rpcRoles) ? rpcRoles : [];
        const list = raw.map((r)=>String(r)).filter(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isRole"]);
        return [
            ...new Set(list)
        ].sort((a, b)=>__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ROLES"].indexOf(a) - __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ROLES"].indexOf(b));
    }
    const { data, error } = await supabase.from("workplace_members").select("role").eq("user_id", user.id).eq("workplace_id", workplaceId);
    if (error) throw error;
    const list = (data ?? []).map((row)=>row.role).filter(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isRole"]);
    return [
        ...new Set(list)
    ].sort((a, b)=>__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ROLES"].indexOf(a) - __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ROLES"].indexOf(b));
}
async function routeRolesForActiveWorkplace(supabase, router, workplaceId) {
    let roles;
    try {
        roles = await fetchUserRolesForWorkplace(supabase, workplaceId);
    } catch  {
        return "fetch_error";
    }
    if (roles.length === 0) return "no_roles";
    if (roles.length === 1) {
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["setActiveRoleCookie"])(roles[0]);
        router.push("/dashboard");
        return "routed";
    }
    router.push("/select-role");
    return "routed";
}
async function routeAfterLogin(supabase, router) {
    if (await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$super$2d$admin$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["hasSuperAdminAccess"])(supabase)) {
        router.push("/select-workplace");
        return "routed";
    }
    let workplaces;
    try {
        workplaces = await fetchUserWorkplaces(supabase);
    } catch  {
        return "fetch_error";
    }
    if (workplaces.length === 0) return "no_workplaces";
    if (workplaces.length === 1) {
        const only = workplaces[0];
        setActiveWorkplaceCookie(only.id);
        return routeRolesForActiveWorkplace(supabase, router, only.id);
    }
    router.push("/select-workplace");
    return "routed";
}
}),
"[project]/src/lib/active-workplace-server.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "resolveActiveWorkplaceNameForSidebar",
    ()=>resolveActiveWorkplaceNameForSidebar
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/headers.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$workplaces$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/workplaces.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/utils/supabase/server.ts [app-rsc] (ecmascript)");
;
;
;
function displayFromRow(row) {
    if (row == null) return null;
    const company = typeof row.company_name === "string" ? row.company_name.trim() : "";
    const shortName = typeof row.name === "string" ? row.name.trim() : "";
    const display = company.length > 0 ? company : shortName;
    return display.length > 0 ? display : null;
}
async function resolveActiveWorkplaceNameForSidebar() {
    const jar = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cookies"])();
    const wpId = jar.get(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$workplaces$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ACTIVE_WORKPLACE_COOKIE"])?.value?.trim();
    if (!wpId) return null;
    try {
        const supabase = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$utils$2f$supabase$2f$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["createServerSupabase"])();
        const full = await supabase.from("workplaces").select("name, company_name").eq("id", wpId).maybeSingle();
        if (!full.error && full.data != null) {
            const d = displayFromRow(full.data);
            if (d) return d;
        }
        if (full.error) {
            const minimal = await supabase.from("workplaces").select("name").eq("id", wpId).maybeSingle();
            if (!minimal.error && minimal.data != null) {
                const d = displayFromRow(minimal.data);
                if (d) return d;
            }
        }
        const { data: rpcRows, error: rpcErr } = await supabase.rpc("get_my_workplaces");
        if (rpcErr || !Array.isArray(rpcRows)) return null;
        const row = rpcRows.find((r)=>r.id === wpId);
        const n = row?.name?.trim();
        return n && n.length > 0 ? n : null;
    } catch  {
        return null;
    }
}
}),
"[project]/app/dashboard/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>DashboardLayout
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/headers.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$admin$2d$workspace$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/admin-workspace-shell.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2d$onboarding$2d$guard$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/dashboard-onboarding-guard.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$active$2d$workplace$2d$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/active-workplace-server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/roles.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$ui$2d$theme$2d$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/ui-theme-server.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/types/roles.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
async function DashboardLayout({ children }) {
    const jar = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$headers$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cookies"])();
    const raw = jar.get(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ACTIVE_ROLE_COOKIE"])?.value;
    const showAdminNav = raw != null && (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$types$2f$roles$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isRole"])(raw) && raw === "ADMIN";
    const initialLayoutTheme = showAdminNav ? await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$ui$2d$theme$2d$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveUiThemeForRequest"])() : undefined;
    const activeWorkplaceName = showAdminNav ? await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$active$2d$workplace$2d$server$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveActiveWorkplaceNameForSidebar"])() : null;
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$admin$2d$workspace$2d$shell$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["AdminWorkspaceShell"], {
        showAdminNav: showAdminNav,
        initialLayoutTheme: initialLayoutTheme,
        activeWorkplaceName: activeWorkplaceName,
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2d$onboarding$2d$guard$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DashboardOnboardingGuard"], {
            children: children
        }, void 0, false, {
            fileName: "[project]/app/dashboard/layout.tsx",
            lineNumber: 31,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/app/dashboard/layout.tsx",
        lineNumber: 26,
        columnNumber: 5
    }, this);
}
}),
"[project]/app/dashboard/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/dashboard/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/node_modules/js-cookie/dist/js.cookie.mjs [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>api
]);
/*! js-cookie v3.0.5 | MIT */ /* eslint-disable no-var */ function assign(target) {
    for(var i = 1; i < arguments.length; i++){
        var source = arguments[i];
        for(var key in source){
            target[key] = source[key];
        }
    }
    return target;
}
/* eslint-enable no-var */ /* eslint-disable no-var */ var defaultConverter = {
    read: function(value) {
        if (value[0] === '"') {
            value = value.slice(1, -1);
        }
        return value.replace(/(%[\dA-F]{2})+/gi, decodeURIComponent);
    },
    write: function(value) {
        return encodeURIComponent(value).replace(/%(2[346BF]|3[AC-F]|40|5[BDE]|60|7[BCD])/g, decodeURIComponent);
    }
};
/* eslint-enable no-var */ /* eslint-disable no-var */ function init(converter, defaultAttributes) {
    function set(name, value, attributes) {
        if (typeof document === 'undefined') {
            return;
        }
        attributes = assign({}, defaultAttributes, attributes);
        if (typeof attributes.expires === 'number') {
            attributes.expires = new Date(Date.now() + attributes.expires * 864e5);
        }
        if (attributes.expires) {
            attributes.expires = attributes.expires.toUTCString();
        }
        name = encodeURIComponent(name).replace(/%(2[346B]|5E|60|7C)/g, decodeURIComponent).replace(/[()]/g, escape);
        var stringifiedAttributes = '';
        for(var attributeName in attributes){
            if (!attributes[attributeName]) {
                continue;
            }
            stringifiedAttributes += '; ' + attributeName;
            if (attributes[attributeName] === true) {
                continue;
            }
            // Considers RFC 6265 section 5.2:
            // ...
            // 3.  If the remaining unparsed-attributes contains a %x3B (";")
            //     character:
            // Consume the characters of the unparsed-attributes up to,
            // not including, the first %x3B (";") character.
            // ...
            stringifiedAttributes += '=' + attributes[attributeName].split(';')[0];
        }
        return document.cookie = name + '=' + converter.write(value, name) + stringifiedAttributes;
    }
    function get(name) {
        if (typeof document === 'undefined' || arguments.length && !name) {
            return;
        }
        // To prevent the for loop in the first place assign an empty array
        // in case there are no cookies at all.
        var cookies = document.cookie ? document.cookie.split('; ') : [];
        var jar = {};
        for(var i = 0; i < cookies.length; i++){
            var parts = cookies[i].split('=');
            var value = parts.slice(1).join('=');
            try {
                var found = decodeURIComponent(parts[0]);
                jar[found] = converter.read(value, found);
                if (name === found) {
                    break;
                }
            } catch (e) {}
        }
        return name ? jar[name] : jar;
    }
    return Object.create({
        set,
        get,
        remove: function(name, attributes) {
            set(name, '', assign({}, attributes, {
                expires: -1
            }));
        },
        withAttributes: function(attributes) {
            return init(this.converter, assign({}, this.attributes, attributes));
        },
        withConverter: function(converter) {
            return init(assign({}, this.converter, converter), this.attributes);
        }
    }, {
        attributes: {
            value: Object.freeze(defaultAttributes)
        },
        converter: {
            value: Object.freeze(converter)
        }
    });
}
var api = init(defaultConverter, {
    path: '/'
});
;
}),
];

//# sourceMappingURL=_0um-rnx._.js.map